spring:
  application:
    name: admin-api

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: false

server:
  port: 8080

app:
  jwt:
    secret: ${JWT_SECRET:change-me}
    access-token-ttl-seconds: 1800
    refresh-token-ttl-seconds: 1209600
    
    
logging:
  level:
    org.springframework.security: DEBUG