spring:
  application:
    name: transcoder-worker

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: false

app:
  storage:
    s3:
      provider: ${S3_PROVIDER:minio} # minio | aws
      bucket: ${S3_BUCKET:app-bucket}
      region: ${S3_REGION:ap-northeast-2}
      access-key: ${S3_ACCESS_KEY:}
      secret-key: ${S3_SECRET_KEY:}
      endpoint: ${S3_ENDPOINT:}
      public-base-url: ${S3_PUBLIC_BASE_URL}

server:
  port: 0