FROM eclipse-temurin:21-jdk AS build
WORKDIR /workspace

COPY gradlew .
COPY gradle gradle
COPY settings.gradle .
COPY build.gradle .
COPY modules modules

RUN chmod +x gradlew
RUN ./gradlew :modules:transcoder-worker:bootJar -x test

FROM eclipse-temurin:21-jre
WORKDIR /app

COPY --from=build /workspace/modules/transcoder-worker/build/libs/*.jar app.jar

ENV TZ=Asia/Seoul
ENTRYPOINT ["java","-jar","/app/app.jar"]